repository: lngn-agile-meetup/lngn-agile-meetup.github.io
theme: jekyll-theme-cayman
title: LNGN Agile Meetup
description: Emsländisches Netzwerk rund um Agile Entwicklung
logo: /allgemeines/logo-2018-web.png
show_downloads: false